### ISSUE TITLE
Criar telas de dicas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-sae#26]
O aplicativo terá uma tela de dicas para cada categoria de interesse, sendo elas atividade física, lazer, sono e alimentação. Independente da tela, o conteúdo mostrado será sempre uma lista de itens, sendo que alguns possuem só texto, outro texto e imagem, outros texto, imagem e vídeos. Cada um dos ítens mostrados possuem um id, que pode ser usado para que o usuário chegue até essa seção da página de dicas se clicar em algum link em qualquer local do app.

O objetivo dessa tarefa é controlar a implementação de todas as páginas de dicas do aplicativo, que serão as seguintes:

- [x] #27
- [x] #28
- [x] #29
- [x] #30

Cada uma dessas telas é acessada a partir da página inicial do app (após login). Cada tela tem um ícone na página inicial.

### Dica

O funcionamento dessas telas será muito parecido com as telas de conteúdo do app-uffs-virtual. Podemos utilizar planilhas online para a gerência desses conteúdos, se isso for mais fácil.

**Comment by stefanimeneghetti** [comment]
Conversamos na última reunião que como as páginas de dicas são quatro páginas exatamente iguais seria possível utilizar apenas uma página para todas o que pode facilitar a manutenção no futuro já que seria necessário alterar apenas uma página e não quatro. Então essa issue é resolvida com o [pull request](https://github.com/practice-uffs/app-saude/pull/35) que adiciona uma página que trata todas as telas de dicas.
