### ISSUE TITLE
Migrar algumas telas do app-covid para o aplicativo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-sae#3]
A partir do repositório do [app-covid](https://github.com/grintex/app-covid), "copiar e colar" algumas telas para o aplicativo app-sae. Em linhas gerais, o que eu acho que vale a pena ser copiado é o seguinte:

- Estilo visual (ícones, imagens, etc)
- Tela inicial (que será depois do login no app-sae) com ícones grandes e que, quando clicados, levam para as telas do app
![image](https://user-images.githubusercontent.com/512405/133442889-6d778bcd-3306-4442-9fa0-2085c47d2b01.png)

- Copiar as telas "Onde procurar atendimento", "Sobre Covid-19", "Medidas de prevenção" e "Atendimento emergencial". Acho que essas telas tem vários elementos visuais e de conteúdo que podemos usar para o nosso app do sae.

**Comment by zorteaadriano** [comment]
@SWE3T, continuando o trabalho que estávamos fazendo, importei as 4 telas do app-covid porém faltaram os ícones e alguns outros detalhes, consegue dar uma revisada nessa tarefa na branch 3? Caso contrário já podemos criar outras branchs a partir da dev para as outras issues.
