### ISSUE TITLE
Alinhamento de conteúdo com a cartilha

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/app-sae#44]
Precisamos definir o conteúdo do app-saúde, estou criando esta issue para definir como vai ficar essa parte.

O @CleissonVieira fará a comunicação com a equipe de conteúdo para definir como tudo deve ser feito.

**Comment by CleissonVieira** [comment]
@GuilhermeGraeff @alissonpeloso 
@stefanimeneghetti Segue abaixo documento com o conteúdo, produzido pela con-con, para nós organizar no aplicativo. 


Conteúdo em texto que pode ser inserido no aplicativo:

https://docs.google.com/document/d/1oB-TrDndOXECTKbpKLsMfuIbmUe32E0rk_2YksgGu0E/edit


https://docs.google.com/document/d/17BAs8SrOzbR3fE7rlrjPFwLbm7SGNTyx8bSPw_vKZ1Q/edit
