### ISSUE TITLE
Alterar ícone app Bem-estar

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-sae#57]
Alterar logo do app com as novas: [LINK](https://drive.google.com/drive/folders/1nW2YXuP1gMqr_qeEQGNalZyuOWUFssZU)

**Comment by GuilhermeGraeff** [comment]
Aguardando a issue [971](https://github.com/practice-uffs/programa/issues/971) do programa finalizar, como ela foi reaberta e tudo, daí teria que abrir outra issue caso eu concluísse esta, mutei o status para "aguardando algo" e vou tirar a label "need review".

Assim podemos trabalhar na mesma branch e tudo.

**Comment by GuilhermeGraeff** [comment]
Ainda estamos aguardando instruções.

**Comment by GuilhermeGraeff** [comment]
Ainda estamos aguardando instruções.
