### ISSUE TITLE
Melhorias de UX/UI no Aplicativo

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-sae#61]
- [x] Acho que devemos mudar a fonte do app, pra ele se tornar mais único e não mais do mesmo.
- [x] Acredito que a forma como o conteúdo está sendo mostrada precisa ser repensado
- [x] Alterar os emojis da tela de estatísticas para ficar igual ao da tela inicial:
![image](https://user-images.githubusercontent.com/51202705/158993820-c08c4657-51a3-4b9e-8817-161a8e3375fd.png)

**Comment by CleissonVieira** [comment]
Ícones ajustados. A fonte  estou em busca de opções para apresentar para a equipe.

O item sobre a forma de mostrar os conteúdos, em conversa com @SWE3T no Telegram, está em andamento na [issue #1136 de Revisão de conteúdo](https://github.com/practice-uffs/programa/issues/1136). Onde conforme ajustes e avaliações está sendo criado novas tarefas para melhorar o design das telas.

**Comment by CleissonVieira** [comment]
Testei diversas fontes, porém, para ```--f7-font-family``` apenas as listadas abaixo funcionaram.
A ```system-ui``` é a que mais se adequou na minha opinião. Porém, é a que se adequá de acordo com a fonte do dispositivo de quem está utilizando pelo que entendi.
Se alguém souber como ajustar e inserir outras fontes. Assim como tiver uma em mente que se fique melhor que a original, por gentileza, informe para nós
Busquei por padrões de boas fontes para aplicativos. Não obtive muito sucesso em minhas pesquisas.

- ```Helvetica```
![image](https://user-images.githubusercontent.com/29258164/161360027-24e15686-cc2e-4dc8-afe7-5bf3a1088045.png)

- ```sans-serif```
![image](https://user-images.githubusercontent.com/29258164/161360048-0bc12e50-6d93-4fa0-b68f-5f142174e677.png)

- ```Roboto```
![image](https://user-images.githubusercontent.com/29258164/161360079-7f442168-d884-4575-a429-58c798491af6.png)

- ```system-ui```
![image](https://user-images.githubusercontent.com/29258164/161360108-0e0ba1c1-3cb2-407b-9bdf-581bac3b40ea.png)

**Comment by alissonpeloso** [comment]
@CleissonVieira, faltou mudar o estado da issue para "aguardando algo"
