### ISSUE TITLE
Mudanças na disposição dos menus

### ISSUE THREAD

**Issue by SWE3T** [practice-uffs/app-sae#62]
Mudanças sugeridas pelo Robison: 

"No lugar de 13 opções na tela inicial, vamos colocar 4 e dentro dessas 4 colocar o resto."

A partir disso, o menu deverá conter os seguintes itens: 

- Transtornos mais comuns; 
- Dicas do SAE; 
- Meditação guiada; 
- Minhas estatísticas:

Referência: 
https://github.com/practice-uffs/programa/issues/1136

**Comment by alissonpeloso** [comment]
@SWE3T, lembra de adicionar a Sprint
