### ISSUE TITLE
Medição dos batimentos cardíacos 

### ISSUE THREAD

**Issue by SWE3T** [practice-uffs/app-sae#66]
É preciso ver se é possível fazer a medição dos batimentos cardíacos no aplicativo.

A tela já está implementada, porém a parte funcional ainda precisa ser feita.

 Eu achei o seguinte link que pode dar um norte para a realização desta tarefa:
https://freesoft.dev/program/106909502

**Comment by alissonpeloso** [comment]
@CleissonVieira, conseguiu utilizar o plugin que o Sweet sugeriu?

**Comment by CleissonVieira** [comment]
> @CleissonVieira, conseguiu utilizar o plugin que o Sweet sugeriu?

Infelizmente não consegui utilizar. O Sweet também tentou instalar a mesma.
Concluímos que o plugin é antigo e não tem mais suporte. O cordova não encontra o mesmo.
Fiz uma busca em cima de outros plugins, não encontrei nenhum que obtive sucesso em instalar e utilizar que possua a mesma finalidade de fazer a medição dos batimentos cardíacos pelo app.

**Comment by SWE3T** [comment]
O Alisson deu uma ideia muito boa: talvez exista algum plugin pelo próprio HTML que faça a medição dos batimentos cardíacos. Ele citou o exemplo do app Practice, que utiliza um plugin do cordova para habilitar a câmera e outro que não está relacionado ao cordova para ler o código QR.
@CleissonVieira

**Comment by alissonpeloso** [comment]
Encontrou algo para JS, @CleissonVieira ?

**Comment by CleissonVieira** [comment]
@alissonpeloso 
Não encontrei, acredito que minhas pesquisao não estão eficientes.
Estava em cima de abrir o app do maps conforme [issue 75](https://github.com/practice-uffs/app-boas-vindas/issues/75)

**Comment by alissonpeloso** [comment]
Só consegui achar pra flutter por enquanto -> https://pub.dev/packages/heart_bpm

**Comment by alissonpeloso** [comment]
Talvez isso seja útil -> https://github.com/gfwilliams/HeartRate

**Comment by alissonpeloso** [comment]
Não consegui encontrar nada, nem mesmo pra js. único que encontrei é esse, para flutter: https://pub.dev/packages/heart_bpm
