### ISSUE TITLE
Trazer a pasta 'WWW' para o repositório

### ISSUE THREAD

**Issue by SWE3T** [practice-uffs/app-sae#76]
O Cleisson teve problemas com a utilização dos CLIs do Cordova, a causa era o projeto não ter uma pasta www que o mesmo precisa para reconhecer o projeto como sendo um projeto Cordova.

**Comment by alissonpeloso** [comment]
@SWE3T, adiciona sempre nos Projects "Geral", se não não aparece no nosso kanban e não consigo mapear a tarefa

**Comment by alissonpeloso** [comment]
@SWE3T, acredito que essa pasta www para reconhecer como projeto cordova é dentro da pasta cordova, não?

**Comment by SWE3T** [comment]
Pelo o que eu vi, no meu projeto ele não está dentro de outras pastas, mas vou verificar assim que chegar em casa.

**Comment by SWE3T** [comment]
Eu corrigi o diretório da pasta. Tinha subido ela no diretório errado mesmo :p
