### ISSUE TITLE
Adicionar novo widget da aura no app

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-sae#86]
Pode se basear nessa issue aqui: https://github.com/practice-uffs/app-practice/issues/219

A ideia é utilizar um iframe e utilizar o token de autenticação sem precisar fazer o login pelo widget.

`v0/widgets/aura` é a rota de acesso pela `API`

**Comment by stefanimeneghetti** [comment]
Conversei com o @SWE3T a respeito dessa issue já que não havia encontrado a página responsável pela Aura no app e ele me disse que  como o app não é focado na universidade a ideia é não utilizar a Aura pelo menos por enquanto. Então acredito que essa issue pode ser fechada no momento e reaberta no futuro se necessário.
